server:
  port: 8091

spring:
  application:
    name: eureka-feign

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
  instance:
    preferIpAddress: true
    instance-id: localhost:${server.port}

info:
  name: eureka-feign
