server:
  port: 8092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
  instance:
    preferIpAddress: true
    instance-id: localhost:${server.port}
spring:
  application:
    name: eureka-client
